{ 
    "hardware" :
    {
      "machine" :
      {
        "service" :
        {
          "module" : "atlas.api.env.hardware.service.DefaultMachineService",
          "classname" : "DefaultMachineService",
	    "name" : "machine"
        },
        "datasource" :
        {
          "nt" :
          {
		  "module": "atlas.api.env.hardware.datasource.impl.windows.WindowsMachineDataSource",
		  "classname" : "WindowsMachineDataSource"
          }
        }
      },
      "network_controller":
      {
        "service" :
        {
          "module" : "atlas.api.env.hardware.service.DefaultNetworkControllerService",
          "classname" : "DefaultNetworkControllerService",
	    "name" : "network_controller"
        },
        "datasource" :
        {
          "nt" :
          {
		"module": "atlas.api.env.hardware.datasource.impl.windows.WindowsNetworkControllerDataSource",
		"classname" : "WindowsNetworkControllerDataSource"
          }
        }
      }
    },
    "networking" :
    {
      "protocol" :
      {
        "service" : 
        {
          "module" : "atlas.api.env.networking.service.DefaultProtocolService",
          "classname" : "DefaultProtocolService",
	    "name" : "protocol"
        },
        "datasource":
        {
          "nt" :
          {
            "module" : "atlas.api.env.networking.datasource.impl.windows.WindowsProtocolDataSource",
            "classname" : "WindowsProtocolDataSource"
          }
        }
      }
    }
  
}
