{
  "windows": 
  {
    "module": "atlas.api.environment.windows",
    "classname": "Windows",
    "host": {
      "name": "coverdale",
      "ip": "192.168.1.2"
    }
  },
  "linux": 
  {
    "module": "atlas.api.environment.linux",
    "classname": "Linux",
    "host": 
    {
      "name": "coverdale",
      "ip": "192.168.1.2"
    },
    "distribution": 
    {
      "name": "Ubuntu",
      "version": "7.10",
      "platform": 
      {
        "type": "32 bits",
        "name": "x86"
      }
    }
  }
}
